#-------------------------------
# General Site Settings
title: Divyesh G. Rajpura
logo: logo.png # You can add own logo.
description: This is my personal website


#-------------------------------
# Author Settings
author:
  name: Divyesh G. Rajpura
  image: profile.png
  say-hello: Hello, Iâ€™m <strong>Divyesh G. Rajpura</strong>
  bio: My area of research is Automatic Speaker Recognition (ASR) and Speaker Diarization. Recent technological advancement of Smart Devices and Voice Assistants has motivated researchers to develop a robust ASR system in adverse conditions such as noisy environment, far-field, short-duration. The key objective of my research is to develop statistical methods and machine learning-based solutions to solve this challenging problem.

#-------------------------------
# Contact links
twitter: https://twitter.com/divyesh_rajpura # Add your Twitter handle
facebook: https://facebook.com/divyesh.rajpura # Add your Facebook handle
instagram: https://instagram.com/divyesh.rajpura # Add your Instagram handle
linkedin: https://linkedin.com/divyeshrajpura4114
github: https://github.com/divyeshrajpura4114
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle

#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-divyeshrajpura # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e